language: php

env:
  global:
    - COMPOSER_ROOT_VERSION=1.x-dev

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL
    - php: 7.0
      env: DB=MYSQL
    - php: 7.1
      env: DB=MYSQL
    - php: 7.2
      env: DB=MYSQL

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer validate
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:2.0.x-dev --no-update; fi
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit --testsuite recipe-reporting-tools
